version: '3'

services:
    nginx:
        image: "cuongnv23/url-shortener-nginx:latest"
        deploy:
            replicas: 2
            placement:
                constraints: [node.role != manager]
            resources:
                limits:
                    cpus: "0.5"
                    memory: 50M
        ports:
            - "8888:80"

    app:
        image: "cuongnv23/url-shortener-app:latest"
        deploy:
            replicas: 2
            placement:
                constraints: [node.role != manager]
        env_file:
            - ./.env
        depends_on:
            - postgres

    postgres:
        image: "cuongnv23/url-shortener-db:latest"
        deploy:
            placement:
                constraints: [node.role == manager]
        env_file:
            - ./.env
        volumes:
            - data:/var/lig/postgres/data
        ports:
            - "5432"

volumes:
    data: