apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: db
  template:
    metadata:
      labels:
        app: postgres
        tier: db
    spec:
      containers:
        - name: postgres
          image: "cuongnv23/url-shortener-db:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: pgdata
          envFrom:
            - configMapRef:
                name: url-config
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
